package TestCases.CRM;

import java.util.Properties;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.ReadTextFile;
import Operation.SeleniumOperation;

public class CCRefund 
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		//OTPCCSuccess otpcc = new OTPCCSuccess(); // Pre-requisite: Need to run OTPCCSuccess script.
		//otpcc.ExecutionStatusCheck();
		//otpcc.testOTPSuccess();
		
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testCCRefund() throws Exception 
	{
		
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		
		try
		{	
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			operation.execute(allObjects, "ACCESSURL", "", "", data[0][2]);
			operation.execute(allObjects, "SENDKEYS", "USERNAME", "name", data[1][2]);
			operation.execute(allObjects, "SENDKEYS", "PASSWD", "name", data[2][2]);
			operation.execute(allObjects, "CLICK", "LOGIN", "id", "");
			operation.execute(allObjects, "CLICK", "CUSTOMERLINK", "link", "");
		
			String location = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\CustomerToRefund.txt";
			String Customer = ReadTextFile.Readdata(location);
			
			operation.execute(allObjects, "SENDKEYS", "COL1ROW4", "css", "Email");
			operation.execute(allObjects, "SENDKEYS", "COL2ROW4", "css", "equals");
			operation.execute(allObjects, "SENDKEYS", "COL3ROW4", "css", Customer);
			operation.execute(allObjects, "CLICK", "SEARCHNOW", "css", "");
			operation.execute(allObjects, "CLICK", "RefundsLink", "xpath", "");
			Thread.sleep(5000);
			
			//Getting values of Amount to Refund and Transaction ID
			String amounttorefund = operation.execute(allObjects, "GETTEXT", "AmounttoRefund", "xpath", "");
			String TransactionID = operation.execute(allObjects, "GETTEXT", "TransactionID", "xpath", "");
			
			//Getting credit_card_transaction_id from database and setting the value for Refund ID and Comments
			String query1 = "SELECT id FROM `credit_card_transaction` WHERE transaction_code = '"+TransactionID+"'";
			String RefundID = SeleniumOperation.querydb(query1, "brandywine_erp");
			String Refund_ID = ".//*[@id='refund_"+RefundID+"']";
			String Comments = ".//*[@id='comments_"+RefundID+"']";
			
			
			webdriver.findElement(By.xpath(Refund_ID)).sendKeys(amounttorefund);
			webdriver.findElement(By.xpath(Comments)).sendKeys("Auto Refund");
			Thread.sleep(2000);
			
			operation.execute(allObjects, "CLICK", "RefundSave", "xpath", "");
			Thread.sleep(5000);
			operation.execute(allObjects, "CLICK", "RefundConf", "xpath", "");
			Thread.sleep(5000);
			
			//Checking the Refund status in database
			String query2="SELECT description FROM `payment_gateway_log` WHERE `transaction_id` = '"+TransactionID+"' ORDER BY date_created DESC LIMIT 1";
			String RefundStatus = SeleniumOperation.querydb(query2, "brandywine_erp");
			Assert.assertEquals(RefundStatus,"VOID");	
			
			operation.execute(allObjects, "CLICK", "MYACCOUNTSELECTOR", "css", "");
			operation.execute(allObjects, "CLICK", "BacktoCRM", "xpath", "");
			operation.execute(allObjects, "CLICK", "CRMLogout", "xpath", "");
			webdriver.quit();
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}	
		
	}
}
