package TestCases.CRM;

import java.util.Calendar;
import java.util.Properties;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

import Operation.CalendarFeatures;
import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.ReadTextFile;
import Operation.SeleniumOperation;

public class CheckRefund 
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testCheckRefund() throws Exception 
	{
		
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		
		try
		{	
			
			int CurDate = CalendarFeatures.getcurrentdate();
			Calendar cal = Calendar.getInstance();
			String Month = String.valueOf(cal.get(Calendar.DAY_OF_MONTH));
			String Hour = String.valueOf(cal.get(Calendar.HOUR));
			String Minutes = String.valueOf(cal.get(Calendar.MINUTE));
			String Seconds = String.valueOf(cal.get(Calendar.SECOND));
			String CheckNumber = Month + Hour + Minutes + Seconds;
			String RefundAmount = "2.00";
			
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			operation.execute(allObjects, "ACCESSURL", "", "", data[0][2]);
			operation.execute(allObjects, "SENDKEYS", "USERNAME", "name", data[1][2]);
			operation.execute(allObjects, "SENDKEYS", "PASSWD", "name", data[2][2]);
			operation.execute(allObjects, "CLICK", "LOGIN", "id", "");
			operation.execute(allObjects, "CLICK", "CUSTOMERLINK", "link", "");
		
			String location = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\CustomerToRefund.txt";
			String Customer = ReadTextFile.Readdata(location);
			
			operation.execute(allObjects, "SENDKEYS", "COL1ROW4", "css", "Email");
			operation.execute(allObjects, "SENDKEYS", "COL2ROW4", "css", "equals");
			operation.execute(allObjects, "SENDKEYS", "COL3ROW4", "css", Customer);
			operation.execute(allObjects, "CLICK", "SEARCHNOW", "css", "");
			operation.execute(allObjects, "CLICK", "RefundsLink", "xpath", "");
			operation.execute(allObjects, "CLICK", "CheckSelector", "xpath", "");
			operation.execute(allObjects, "CLICK", "CheckRefundCalendar", "xpath", "");
			
			String calendarXpath = "//td[not(contains(@class,'ui-datepicker-days-cell-over ui-datepicker-today'))]/a[text()='"+CurDate+"']";
			operation.executedynamicobject("CLICK", calendarXpath, "xpath", "");
			
			operation.execute(allObjects, "SENDKEYS", "CheckNumber", "xpath", CheckNumber);
			operation.execute(allObjects, "SENDKEYS", "CheckRefundComments", "xpath", "Auto Refund");
			operation.execute(allObjects, "SENDKEYS", "CheckRefundAmt", "xpath", RefundAmount);
			operation.execute(allObjects, "CLICK", "RefundSave", "xpath", "");
			operation.execute(allObjects, "CLICK", "RefundConf", "xpath", "");
			String message = operation.execute(allObjects, "GETTEXT", "RefundSuccessMsg", "xpath", "");
			Thread.sleep(5000);
			
			//Getting check number from database (ERP > "refund_check" table)
			String query1 = "SELECT number FROM `refund_check` WHERE customer_id = (SELECT id FROM customer WHERE email = '"+Customer+"') ORDER BY date_created DESC LIMIT 1";
			String Check = SeleniumOperation.querydb(query1, "brandywine_erp");
						
			//Getting check number from database (ERP > "refund_check" table)
			String query2 = "SELECT amount FROM `refund_check` WHERE customer_id = (SELECT id FROM customer WHERE email = '"+Customer+"') ORDER BY date_created DESC LIMIT 1";
			String AmtRefunded = SeleniumOperation.querydb(query2, "brandywine_erp");
			
			Assert.assertEquals(Check, CheckNumber);
			Assert.assertEquals(AmtRefunded, RefundAmount);	
			Assert.assertEquals(message, "Refund applied successfully.");
			
			operation.execute(allObjects, "CLICK", "MYACCOUNTSELECTOR", "css", "");
			operation.execute(allObjects, "CLICK", "BacktoCRM", "xpath", "");
			webdriver.quit();
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}	
		
	}

}
