package TestCases.CRM;

import java.util.Iterator;
import java.util.Properties;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.SeleniumOperation;
import Operation.WriteTextFile;

public class CreateTicket 
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testCreateTicket() throws Exception 
	{
		
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		re.setInputFile(xllocation, 8);
		String[][] values = re.readFile();
						
		try
		{	
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			operation.execute(allObjects, "ACCESSURL", "", "", data[0][2]);
			operation.execute(allObjects, "SENDKEYS", "USERNAME", "name", data[1][2]);
			operation.execute(allObjects, "SENDKEYS", "PASSWD", "name", data[2][2]);
			operation.execute(allObjects, "CLICK", "LOGIN", "id", "");
			operation.execute(allObjects, "CLICK", "CreateTicket", "xpath", "");
			operation.execute(allObjects, "SENDKEYS", "SourceSelection", "xpath", values[1][1]);
			operation.execute(allObjects, "SENDKEYS", "Direction", "xpath", values[1][2]);
			operation.execute(allObjects, "CLICK", "CustomerAdd", "xpath", "");

			//Switching control to dialog window
			Iterator<String> itr = webdriver.getWindowHandles().iterator();
			String main = itr.next();
			String popup = itr.next();
			webdriver.switchTo().window(popup);
			Thread.sleep(5000);
			
			operation.execute(allObjects, "SENDKEYS", "EmailEntry", "xpath", values[1][3]);
			operation.execute(allObjects, "CLICK", "SearchNowButton", "xpath", "");
			Thread.sleep(5000);
			operation.execute(allObjects, "CLICK", "CustomerSelect", "xpath", "");
			Thread.sleep(5000);
			
			//Switching back control to main window
			webdriver.switchTo().window(main);
			
			operation.execute(allObjects, "SENDKEYS", "Subject", "xpath", values[1][4]);
			operation.execute(allObjects, "SENDKEYS", "Reason", "xpath", values[1][5]);
			operation.execute(allObjects, "SENDKEYS", "TicketStatus", "xpath", values[1][6]);
			operation.execute(allObjects, "SENDKEYS", "AssignedTo", "xpath", values[1][7]);
			operation.execute(allObjects, "SENDKEYS", "Priority", "xpath", values[1][8]);
			operation.execute(allObjects, "SENDKEYS", "AddNotes", "xpath", values[1][9]);
			operation.execute(allObjects, "CLICK", "TicketSave", "xpath", "");
			Thread.sleep(5000);
			
			String ticket_number = operation.execute(allObjects, "GETTEXT", "TicketNumber", "xpath", "");
						
			//Writing ticket details to a text file.
			WriteTextFile objWrite = new WriteTextFile();
			String filePath = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\TicketDetails.txt";
			objWrite.Writedata(filePath, ticket_number);
			
			webdriver.quit();			
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}	
		
	}
}
