package TestCases.CRM;

import java.util.Properties;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.SeleniumOperation;
import Operation.WriteTextFile;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

public class DonationRecurring 
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testDonationRecurring() throws Exception 
	{
		
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		
		try
		{	
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			operation.execute(allObjects, "ACCESSURL", "", "", data[0][2]);
			operation.execute(allObjects, "SENDKEYS", "USERNAME", "name", data[1][2]);
			operation.execute(allObjects, "SENDKEYS", "PASSWD", "name", data[2][2]);
			operation.execute(allObjects, "CLICK", "LOGIN", "id", "");
			operation.execute(allObjects, "CLICK", "CUSTOMERLINK", "link", "");
			
			//String query ="SELECT email FROM customer WHERE is_active='1' LIMIT 1";
			String query = "SELECT c.email FROM customer c, credit_card cc WHERE c.id = cc.customer_id AND c.billing_method = 'AUTHORIZE_DOT_NET' AND c.is_active = 1 AND cc.is_active = 1 AND cc.expiry_date > CURDATE() LIMIT 1";
			String cust= SeleniumOperation.querydb(query, "brandywine_erp");
					
			operation.execute(allObjects, "SENDKEYS", "COL1ROW4", "css", "Email");
			operation.execute(allObjects, "SENDKEYS", "COL2ROW4", "css", "equals");
			operation.execute(allObjects, "SENDKEYS", "COL3ROW4", "css", cust);
			operation.execute(allObjects, "CLICK", "SEARCHNOW", "css", "");
			
			String region= operation.execute(allObjects, "GETTEXT", "region", "xpath", "");	
								
			operation.execute(allObjects, "CLICK", "DonateLink", "xpath", "");
			operation.execute(allObjects, "CLICK", "Donatenow", "css", "");
				
				if(region == "LA")
				{
					operation.execute(allObjects, "CLICK", "servicesizela", "css", "");
				}
				else
				{
					operation.execute(allObjects, "CLICK", "servicesizesf", "css", "");
				}
			
			operation.execute(allObjects, "CLICK", "recurring", "css", "");
			operation.execute(allObjects, "SELECTBYINDEX", "Recurringfrequency", "css", "");
			operation.execute(allObjects, "SELECTBYINDEX", "RecurringStartDate", "css", "");
			operation.execute(allObjects, "CLICK", "Recurringafter", "css", "");
			operation.execute(allObjects, "SENDKEYS", "Noofdonations", "css", "2");
			Thread.sleep(10000);
			operation.execute(allObjects, "CLICK", "donate", "css", "");
			Thread.sleep(5000);
				
				//writing donation number to notepad file
				String donationno= operation.execute(allObjects, "GETTEXT", "Donationnumber", "xpath", "");	
				WriteTextFile objWrite = new WriteTextFile();
				String filePath = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\DonationRecurring.txt";
				objWrite.Writedata(filePath, donationno);
				
			operation.execute(allObjects, "CLICK", "BacktoCRM", "xpath", "");	
			webdriver.quit();
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}	
		
	}
	
}
