package TestCases.CRM;

import java.util.Properties;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.SeleniumOperation;
import Operation.WriteTextFile;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

public class GiftCertificateByEmail 
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
		public void testGiftCertificateByEmail() throws Exception 
		{
			
			ReadExcel re = new ReadExcel();
			String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
			re.setInputFile(xllocation, 0);
			String[][] data = re.readFile();
			
			try
			{	
				//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
				operation.execute(allObjects, "ACCESSURL", "", "", data[0][2]);
				operation.execute(allObjects, "SENDKEYS", "USERNAME", "name", data[1][2]);
				operation.execute(allObjects, "SENDKEYS", "PASSWD", "name", data[2][2]);
				operation.execute(allObjects, "CLICK", "LOGIN", "id", "");
				operation.execute(allObjects, "CLICK", "CUSTOMERLINK", "link", "");
					
				String query ="SELECT email FROM customer WHERE is_active='1' LIMIT 1";
				String cust= SeleniumOperation.querydb(query, "brandywine_erp");
						
				operation.execute(allObjects, "SENDKEYS", "COL1ROW4", "css", "Email");
				operation.execute(allObjects, "SENDKEYS", "COL2ROW4", "css", "equals");
				operation.execute(allObjects, "SENDKEYS", "COL3ROW4", "css", cust);
				operation.execute(allObjects, "CLICK", "SEARCHNOW", "css", "");
				operation.execute(allObjects, "CLICK", "GCLink", "xpath", "");
				operation.execute(allObjects, "SENDKEYS", "GCzip", "id", "90001");
				operation.execute(allObjects, "CLICK", "GCzipsearch", "id", "");
				operation.execute(allObjects, "CLICK", "GCgetstarted", "id", "");
						
				//By Email
					
				operation.execute(allObjects, "SENDKEYS", "recipientfn", "css", "Automated");
				operation.execute(allObjects, "SENDKEYS", "recipientln", "css", "Gift Certificate");
				operation.execute(allObjects, "SENDKEYS", "recipientmsg", "css", "This is an auto generated GC");
				operation.execute(allObjects, "SENDKEYS", "GCamount", "css", "30");
				operation.execute(allObjects, "SENDKEYS", "ByEmailFrom", "css", "By Email Auto Customer");
				operation.execute(allObjects, "SENDKEYS", "ByEmailTo", "css", "sibin@neevtech.com");
				operation.execute(allObjects, "SENDKEYS", "ByEmailConfRecipient", "css", "sibin@neevtech.com");
				operation.execute(allObjects, "CLICK", "CheckOut", "css", "");
				operation.execute(allObjects, "CLEAR", "GCBillingEmail", "xpath", "");
				operation.execute(allObjects, "SENDKEYS", "GCBillingEmail", "xpath", cust);
				operation.execute(allObjects, "SELECTBYINDEX", "OTPCCType", "css", "MasterCard");
				operation.execute(allObjects, "CLEAR", "OTPCCNumber", "css", "");
				operation.execute(allObjects, "SENDKEYS", "OTPCCNumber", "css", "5555555555554444");	
				operation.execute(allObjects, "SELECTBYINDEX", "OTPExpMonth", "css", "");	
				operation.execute(allObjects, "SELECTBYINDEX", "OTPExpYear", "css", "");
				operation.execute(allObjects, "CLEAR", "OTPSecurityCode", "css", "123");	
				operation.execute(allObjects, "SENDKEYS", "OTPSecurityCode", "css", "123");	
				operation.execute(allObjects, "CLICK", "GCsubmit", "css", "");
				operation.execute(allObjects, "CLICK", "GCpurchaseconf", "css", "");
					
					//writing GC Number number to notepad file
					String GCno= operation.execute(allObjects, "GETTEXT", "GCNumber", "xpath", "");	
					WriteTextFile objWrite = new WriteTextFile();
					String filePath = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\GiftCertificateByEmail.txt";
					objWrite.Writedata(filePath, GCno);
						
				operation.execute(allObjects, "CLICK", "BacktoCRM", "xpath", "");	
				webdriver.quit();
			}
			catch (NoSuchElementException e) 
			{	
				e.printStackTrace();
				webdriver.quit();
			}	
			
		}
}
