package TestCases.Common;

import java.util.Properties;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.ReadTextFile;
import Operation.SeleniumOperation;


public class VerifyStaticLinks 
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testVerifyStaticLinks() throws Exception 
	{
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		re.setInputFile(xllocation, 7);
		String[][] values = re.readFile();
		
		try
			{	
				//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
				String location1 = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\Subscription.txt";
				String loginemail = ReadTextFile.Readdata(location1);
				
				//Logging to Magento portal 
				operation.execute(allObjects, "ACCESSURL", "", "", data[0][1]);
				operation.execute(allObjects, "SENDKEYS", "ENTEREMAIL", "id", loginemail);
				operation.execute(allObjects, "SENDKEYS", "ENTERPASSWORD", "id", data[2][1]);
				operation.execute(allObjects, "CLICK", "LOGINBUTTON", "id", "");
				Thread.sleep(5000);
				
				//OUR FARM links
				operation.execute(allObjects, "CLICK", "OurFarm", "xpath", "");
				operation.execute(allObjects, "CLICK", "AboutOurFarm", "xpath", "");
				Thread.sleep(5000);
				String title1 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title1);
				System.out.println(values[0][0]);
				assert(values[0][0].equalsIgnoreCase(title1));
				
				operation.execute(allObjects, "CLICK", "OurFarm", "xpath", "");
				operation.execute(allObjects, "CLICK", "FarmNews", "xpath", "");
				Thread.sleep(5000);
				String title16 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title16);
				assert(values[0][15].equalsIgnoreCase(title16));
				
				operation.execute(allObjects, "CLICK", "OurFarm", "xpath", "");
				operation.execute(allObjects, "CLICK", "CertifiedOrganic", "xpath", "");
				Thread.sleep(5000);
				String title2 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title2);
				assert(values[0][1].equalsIgnoreCase(title2));
				
				operation.execute(allObjects, "CLICK", "OurFarm", "xpath", "");
				operation.execute(allObjects, "CLICK", "WhatWeGrow", "xpath", "");
				Thread.sleep(5000);
				String title3 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title3);
				assert(values[0][2].equalsIgnoreCase(title3));
				
				operation.execute(allObjects, "CLICK", "OurFarm", "xpath", "");
				operation.execute(allObjects, "CLICK", "WhereToFindUs", "xpath", "");
				Thread.sleep(5000);
				String title4 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title4);
				assert(values[0][3].equalsIgnoreCase(title4));
				
				//OUR STORY links
				operation.execute(allObjects, "CLICK", "OurStory", "xpath", "");
				operation.execute(allObjects, "CLICK", "AboutUs", "xpath", "");
				Thread.sleep(5000);
				String title5 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title5);
				assert(values[0][4].equalsIgnoreCase(title5));
				
				//FARMBOX links
				operation.execute(allObjects, "CLICK", "FarmBox", "xpath", "");
				operation.execute(allObjects, "CLICK", "HomeDelivery", "xpath", "");
				Thread.sleep(5000);
				String title20 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title20);
				assert(values[0][19].equalsIgnoreCase(title20));
				
				operation.execute(allObjects, "CLICK", "FarmBox", "xpath", "");
				operation.execute(allObjects, "CLICK", "OfficeDelivery", "xpath", "");
				Thread.sleep(5000);
				String title6 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title6);
				assert(values[0][5].equalsIgnoreCase(title6));
				
				operation.execute(allObjects, "CLICK", "FarmBox", "xpath", "");
				operation.execute(allObjects, "CLICK", "CustomizeYourBox", "xpath", "");
				Thread.sleep(5000);
				String title21 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupB", "xpath", "");
				System.out.println("Verifying title "+title21);
				assert(values[0][20].equalsIgnoreCase(title21));
				
				operation.execute(allObjects, "CLICK", "FarmBox", "xpath", "");
				operation.execute(allObjects, "CLICK", "WhyChooseUs", "xpath", "");
				Thread.sleep(5000);
				String title7 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title7);
				assert(values[0][6].equalsIgnoreCase(title7));
				
				operation.execute(allObjects, "CLICK", "FarmBox", "xpath", "");
				operation.execute(allObjects, "CLICK", "HowItWorks", "xpath", "");
				Thread.sleep(5000);
				String title8 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title8);
				assert(values[0][7].equalsIgnoreCase(title8));
				
				operation.execute(allObjects, "CLICK", "FarmBox", "xpath", "");
				operation.execute(allObjects, "CLICK", "FAQ", "xpath", "");
				Thread.sleep(5000);
				String title9 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title9);
				assert(values[0][8].equalsIgnoreCase(title9));
				
				operation.execute(allObjects, "CLICK", "FarmBox", "xpath", "");
				operation.execute(allObjects, "CLICK", "eGiftCards", "xpath", "");
				Thread.sleep(5000);
				String title22 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupC", "xpath", "");
				System.out.println("Verifying title "+title22);
				assert(values[0][21].equalsIgnoreCase(title22));
				
				//COMMUNITY links
				operation.execute(allObjects, "CLICK", "Community", "xpath", "");
				operation.execute(allObjects, "CLICK", "DonateABox", "xpath", "");
				Thread.sleep(5000);
				String title23 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupD", "xpath", "");
				System.out.println("Verifying title "+title23);
				assert(values[0][22].equalsIgnoreCase(title23));
				
				operation.execute(allObjects, "CLICK", "Community", "xpath", "");
				operation.execute(allObjects, "CLICK", "ReferAFriend", "xpath", "");
				Thread.sleep(5000);
				String title24 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupE", "xpath", "");
				System.out.println("Verifying title "+title24);
				assert(values[0][23].equalsIgnoreCase(title24));
				
				operation.execute(allObjects, "CLICK", "Community", "xpath", "");
				operation.execute(allObjects, "CLICK", "FarmEvents", "xpath", "");
				Thread.sleep(5000);
				String title17 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title17);
				assert(values[0][16].equalsIgnoreCase(title17));
				
				operation.execute(allObjects, "CLICK", "Community", "xpath", "");
				operation.execute(allObjects, "CLICK", "HostYourEvent", "xpath", "");
				Thread.sleep(5000);
				String title10 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title10);
				assert(values[0][9].equalsIgnoreCase(title10));
				
				operation.execute(allObjects, "CLICK", "Community", "xpath", "");
				operation.execute(allObjects, "CLICK", "OurNews", "xpath", "");
				Thread.sleep(5000);
				String title11 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title11);
				assert(values[0][10].equalsIgnoreCase(title11));
				
				operation.execute(allObjects, "CLICK", "Community", "xpath", "");
				operation.execute(allObjects, "CLICK", "Testimonials", "xpath", "");
				Thread.sleep(5000);
				String title12 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title12);
				assert(values[0][11].equalsIgnoreCase(title12));
				
				//RESOURCES links
				operation.execute(allObjects, "CLICK", "Resources", "xpath", "");
				operation.execute(allObjects, "CLICK", "Recipes", "xpath", "");
				Thread.sleep(5000);
				String title18 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title18);
				assert(values[0][17].equalsIgnoreCase(title18));
				
				operation.execute(allObjects, "CLICK", "Resources", "xpath", "");
				operation.execute(allObjects, "CLICK", "StorageandUsageTips", "xpath", "");
				Thread.sleep(5000);
				String title13 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title13);
				assert(values[0][12].equalsIgnoreCase(title13));
				
				String winHandleprimary = webdriver.getWindowHandle(); //Getting the current window handle
				operation.execute(allObjects, "CLICK", "Resources", "xpath", "");
				operation.execute(allObjects, "CLICK", "OurBlog", "xpath", "");
				for(String winHandle : webdriver.getWindowHandles())
				{
				    webdriver.switchTo().window(winHandle);
				    Thread.sleep(5000);
				}
				webdriver.close(); //Closing the new window.
				webdriver.switchTo().window(winHandleprimary); // Switching back to original browser (first window)
				
				operation.execute(allObjects, "CLICK", "Resources", "xpath", "");
				operation.execute(allObjects, "CLICK", "WhyOrganic", "xpath", "");
				Thread.sleep(5000);
				String title14 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title14);
				assert(values[0][13].equalsIgnoreCase(title14));
				
				operation.execute(allObjects, "CLICK", "Resources", "xpath", "");
				operation.execute(allObjects, "CLICK", "Links", "xpath", "");
				Thread.sleep(5000);
				String title15 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupA", "xpath", "");
				System.out.println("Verifying title "+title15);
				assert(values[0][14].equalsIgnoreCase(title15));
				
				Thread.sleep(5000);
				String winHandleBefore = webdriver.getWindowHandle(); //Getting the current window handle
				operation.execute(allObjects, "CLICK", "Resources", "xpath", "");
				operation.execute(allObjects, "CLICK", "ContactUs", "xpath", "");
				// Switch to newly opened window
				for(String winHandle : webdriver.getWindowHandles())
					{
					    webdriver.switchTo().window(winHandle);
					    Thread.sleep(10000);
					}
				String title19 = operation.execute(allObjects, "GETTEXT", "StaticTitlesGroupF", "xpath", "");
				System.out.println("Verifying title "+title19);
				assert(values[0][18].equalsIgnoreCase(title19));
				webdriver.close(); //Closing the new window.
				webdriver.switchTo().window(winHandleBefore); // Switching back to original browser (first window)
				webdriver.quit();
			}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}
		
	}
}
