package TestCases.Magento;

import java.util.Properties;

import org.openqa.selenium.WebDriver;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.ReadTextFile;
import Operation.SeleniumOperation;

import java.util.NoSuchElementException;

public class AddSubscription
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testAddSubscription() throws Exception 
	{
		
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		
		try 
		{
			String location = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\Subscription.txt";
			String loginemail = ReadTextFile.Readdata(location);
		
	
			String query1 = "SELECT COUNT(id) FROM subscription WHERE customer_id = (SELECT id FROM customer WHERE email = '"+loginemail+"') AND is_active = '1'";
			String result1 = SeleniumOperation.querydb(query1, "brandywine_erp");
			int count1 = Integer.parseInt(result1);
			
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			operation.execute(allObjects, "ACCESSURL", "", "", data[0][1]);
			operation.execute(allObjects, "SENDKEYS", "ENTEREMAIL", "id", loginemail);
			operation.execute(allObjects, "SENDKEYS", "ENTERPASSWORD", "id", data[2][4]);
			operation.execute(allObjects, "CLICK", "LOGINBUTTON", "id", "");
			operation.execute(allObjects, "CLICK", "MyAccountlink", "css", "");
			Thread.sleep(5000);
			operation.execute(allObjects, "CLICK", "Editonmanageservice", "xpath", "");
			Thread.sleep(5000);
			operation.execute(allObjects, "CLICK", "SelectandAdd", "css", "");
			operation.execute(allObjects, "CLICK", "Servicesize", "xpath", "");
			operation.execute(allObjects, "SENDKEYS", "FREQUENCY", "id", "Weekly");
			operation.execute(allObjects, "SELECTBYINDEX", "DATE", "id", "");
			operation.execute(allObjects, "CLICK", "Continuetoadd", "css", "");	
				
			//Adding mini service to the subscription
			operation.execute(allObjects, "CLICK", "Addmini", "xpath", "");
			operation.execute(allObjects, "CLICK", "AddSubscriptionSave", "id", "");
				
				String query2 = "SELECT COUNT(id) FROM subscription WHERE customer_id = (SELECT id FROM customer WHERE email = '"+loginemail+"') AND is_active = '1'";
				String result2 = SeleniumOperation.querydb(query2, "brandywine_erp");
				int count2 = Integer.parseInt(result2);
				int compare=count1+2;
				
				//Comparing if active subscription count is matching from database
				Assert.assertEquals(count2,compare);
			operation.execute(allObjects, "CLICK", "LOGOUT", "css", "");
			webdriver.quit();
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}	
	
	}
}
