//Run this script after executing "AddSubscription"

package TestCases.Magento;

import java.util.Properties;

import org.openqa.selenium.WebDriver;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.ReadTextFile;
import Operation.SeleniumOperation;
//import TestCases.Magento.AddSubscription;

import java.util.NoSuchElementException;

public class DeleteSubscription
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		//AddSubscription as= new AddSubscription(); //Prerequisite is to have 2 or more subscription.
		//as.ExecutionStatusCheck();
		//as.testAddSubscription(); 
		
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testDeleteSubscription() throws Exception 
	{
			
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		
		try 
		{
			String location = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\Subscription.txt";
			String loginemail = ReadTextFile.Readdata(location);
	
			String query1 = "SELECT count(id) FROM subscription WHERE customer_id = (SELECT id FROM customer WHERE email = '"+loginemail+"') AND is_active = '1' AND subscription_id IS NULL";
			String result1 = SeleniumOperation.querydb(query1, "brandywine_erp");
			int count = Integer.parseInt(result1);
			System.out.println(count);
			
			if (count >= 2)
			{
			
				//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
				operation.execute(allObjects, "ACCESSURL", "", "", data[0][1]);
				operation.execute(allObjects, "SENDKEYS", "ENTEREMAIL", "id", loginemail);
				operation.execute(allObjects, "SENDKEYS", "ENTERPASSWORD", "id", data[2][4]);
				operation.execute(allObjects, "CLICK", "LOGINBUTTON", "id", "");
				operation.execute(allObjects, "CLICK", "MyAccountlink", "css", "");
				operation.execute(allObjects, "CLICK", "Editonmanageservice", "xpath", "");
				
				String query2 = "SELECT magento_customer_subscription_id FROM subscription WHERE customer_id = (SELECT id FROM customer WHERE email = '"+loginemail+"') AND is_active = '1' AND subscription_id IS NULL ORDER BY magento_customer_subscription_id DESC LIMIT 1";	
				String result2 = SeleniumOperation.querydb(query2, "brandywine_erp");
				
				String subscriptionediturl = "http://www-stag.farmfreshtoyou.com/customer/account/editsubscription/?subscription_id="+result2;
				webdriver.get(subscriptionediturl);
				
				operation.execute(allObjects, "CLICK", "CanceService", "css", "");
				operation.execute(allObjects, "CLICK", "CancelServiceConf", "css", "");
			}
			else
			{
					System.out.println("Base service cannot be cancelled");
					webdriver.quit();
			}
			
			Thread.sleep(5000);
			String query3 = "SELECT count(id) FROM subscription WHERE customer_id = (SELECT id FROM customer WHERE email = '"+loginemail+"') AND is_active = '1' AND subscription_id IS NULL";
			String result3 = SeleniumOperation.querydb(query3, "brandywine_erp");
			int count3 = Integer.parseInt(result3);
			int compare=count-1;
						
			Assert.assertEquals(count3,compare);
				
			operation.execute(allObjects, "CLICK", "LOGOUT", "css", "");
			webdriver.quit();
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}
		
	}
}
