package TestCases.Magento;

import java.util.Calendar;
import java.util.Properties;

import org.openqa.selenium.WebDriver;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.SeleniumOperation;
import Operation.WriteTextFile;

import java.util.NoSuchElementException;

import junit.framework.Assert;

public class GuestGCPurchaseByHand
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testGuestGCPurchaseByHand() throws Exception 
	{
		
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		
		try 
		{
			Calendar cal = Calendar.getInstance();
			//Email contains year + day of month + month + hour + minute + seconds
			String email = "onlinecust"+cal.get(Calendar.YEAR)+cal.get(Calendar.DAY_OF_MONTH)+(cal.get(Calendar.MONTH)+1)+cal.get(Calendar.HOUR)+cal.get(Calendar.MINUTE)+cal.get(Calendar.SECOND)+"@yopmail.com";
			
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			operation.execute(allObjects, "ACCESSURL", "", "", data[0][4]);
			operation.execute(allObjects, "CLICK", "FarmBox", "xpath", "");
			operation.execute(allObjects, "CLICK", "eGiftCards", "xpath", "");
			operation.execute(allObjects, "SENDKEYS", "GCzip", "id", "90001");
			operation.execute(allObjects, "CLICK", "GCzipsearch", "id", "");
			operation.execute(allObjects, "CLICK", "GCgetstarted", "id", "");
			operation.execute(allObjects, "SENDKEYS", "recipientfn", "css", "Automated");
			operation.execute(allObjects, "SENDKEYS", "recipientln", "css", "Gift Certificate");
			operation.execute(allObjects, "SENDKEYS", "recipientmsg", "css", "This is an auto generated GC");
			operation.execute(allObjects, "SENDKEYS", "GCamount", "css", "30");
			operation.execute(allObjects, "CLICK", "ByHand", "css", "");
			operation.execute(allObjects, "SENDKEYS", "GCFrom", "css", "By Hand Auto Customer");
			operation.execute(allObjects, "SENDKEYS", "GCEmail", "css","Byhandautocustomer@yopmail.com");
			operation.execute(allObjects, "SENDKEYS", "GCConfEmail", "css", "Byhandautocustomer@yopmail.com");
			operation.execute(allObjects, "CLICK", "CheckOut", "css", "");
			operation.execute(allObjects, "SENDKEYS", "GuestGCFN", "css", "Guest");
			operation.execute(allObjects, "SENDKEYS", "GuestGCLN", "css", "Automation Customer");
			operation.execute(allObjects, "SENDKEYS", "GuestGCBillingAddr", "css", "720 East 78th Street");
			operation.execute(allObjects, "SENDKEYS", "GuestGCZip", "css", "90001");
			operation.execute(allObjects, "SENDKEYS", "GuestGCEmail", "css", email);
			operation.execute(allObjects, "SELECTBYINDEX", "OTPCCType", "css", "MasterCard");
			operation.execute(allObjects, "CLEAR", "OTPCCNumber", "css", "");
			operation.execute(allObjects, "SENDKEYS", "OTPCCNumber", "css", "5555555555554444");	
			operation.execute(allObjects, "SELECTBYINDEX", "OTPExpMonth", "css", "");	
			operation.execute(allObjects, "SELECTBYINDEX", "OTPExpYear", "css", "");
			operation.execute(allObjects, "SENDKEYS", "OTPSecurityCode", "css", "123");	
			operation.execute(allObjects, "CLICK", "GCsubmit", "css", "");
			operation.execute(allObjects, "CLICK", "GCpurchaseconf", "css", "");
			
			Thread.sleep(5000);
			//writing GC Number number to notepad file
			String GCno= operation.execute(allObjects, "GETTEXT", "GCNumber", "xpath", "");	
			WriteTextFile objWrite = new WriteTextFile();
			String filePath = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\GuestGiftCertificateByHand.txt";
			objWrite.Writedata(filePath, GCno);
			
			String query = "SELECT customer_type FROM customer WHERE email = '"+email+"'";
			String customer_type = SeleniumOperation.querydb(query, "brandywine_erp");
			Assert.assertEquals("Guest", customer_type);
						
			webdriver.quit();
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}	
		
	}
}
