package TestCases.Magento;

import java.util.Properties;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.ReadTextFile;
import Operation.SeleniumOperation;

public class SignupEmailConfirmationCheck 
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testSignupEmailConfirmationCheck() throws Exception 
	{
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		String location = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\Subscription.txt";
		String email = ReadTextFile.Readdata(location);
		
		try
			{	
				
				operation.execute(allObjects, "ACCESSURL", "", "", data[0][6]);
				operation.execute(allObjects, "SENDKEYS", "YopmailTextBox", "xpath", email);
				operation.execute(allObjects, "CLICK", "YopmailCheckInbox", "xpath", "");
				Thread.sleep(5000);
				operation.execute(allObjects, "SWICTHTOIFRAME", "LHSFrame", "id", "");
				operation.execute(allObjects, "CLICK", "FirstEmailSelection", "xpath", "");
				operation.execute(allObjects, "SWITCHFROMIFRAME", "", "", "");
				operation.execute(allObjects, "SWICTHTOIFRAME", "RHSFrame", "id", "");
				
				String title="Welcome to Farm Fresh To You";
				String emailtitle = operation.execute(allObjects, "GETTEXT", "YopmailEmailTitle", "xpath", "");
				Thread.sleep(5000);
				Assert.assertEquals(title,emailtitle);
				System.out.println("Title is as expected");
				
				String emaildisplayed = operation.execute(allObjects, "GETTEXT", "EmailtoCompare", "xpath", "");
				Thread.sleep(5000);
				Assert.assertEquals(email,emaildisplayed);
				System.out.println("Email is as expected");
				
				//operation.perform(allObjects, "CLICK", "EmailLinkToClick", "xpath", "");
				Thread.sleep(5000);
				webdriver.quit();
				
			}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}
		
	}
}
