//Pre-Requisite: Created a jpg file with the name that is provided in the below file 
//E:\eclipse\Automation\Brandywine\TestData\AutogeneratedTestData\TRNumber.txt

package TestCases.SalesRep;

import java.util.Properties;

import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.ReadTextFile;
import Operation.SeleniumOperation;

public class UploadTR 
{
	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testUploadTR() throws Exception 
	{
		
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		
		try 
		{
			String location = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\TRNumber.txt";
			String TRNumber = ReadTextFile.Readdata(location);
			
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			operation.execute(allObjects, "ACCESSURL", "", "", data[0][5]);
			operation.execute(allObjects, "SENDKEYS", "salesemailid", "id", data[1][5]);	
			operation.execute(allObjects, "SENDKEYS", "salespassword", "id", data[2][5]);	
			operation.execute(allObjects, "CLICK", "salesloginbutton", "id", "");	
			
			//Confirming to windows alert
			webdriver.switchTo().alert().accept();
			operation.execute(allObjects, "CLICK", "UploadTRTab", "xpath", "");
			operation.execute(allObjects, "SENDKEYS", "EnterTRNumber", "xpath", TRNumber);
			System.out.println(TRNumber);
			operation.execute(allObjects, "CLICK", "BrowseFile", "xpath", "");
			Thread.sleep(15000);
			
			//Creating PDF file for the script to upload with mentioned TR Number.
			SeleniumOperation.CreatePDFFile(TRNumber);
			Thread.sleep(5000);
			
	        //Code to attach file using Robot functions
			SeleniumOperation.RobotUploadFile(TRNumber+".pdf");
			Thread.sleep(10000);
			
			operation.execute(allObjects, "CLICK", "FileSubmit", "xpath", "");
			Thread.sleep(5000);
			operation.execute(allObjects, "CLICK", "saleslogout", "css", "");
			webdriver.quit();
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}
		
	}

}
