package TestCases.ERP;

import java.util.Calendar;
import java.util.Properties;

import Operation.ExecutionStatusChecker;
import Operation.Launchbrowser;
import Operation.ReadExcel;
import Operation.ReadObjectRepository;
import Operation.SeleniumOperation;
import Operation.WriteTextFile;

import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;

public class CheckDeposit {

	static WebDriver webdriver;
	static Properties allObjects;
	static SeleniumOperation operation;
	String className = getClass().getName();
		
	@BeforeClass
	public void ExecutionStatusCheck() throws Exception
	{
		boolean status = ExecutionStatusChecker.getExecutionStatus(className);
		ExecutionStatusChecker.executetestcase(className, status);
		webdriver=Launchbrowser.launchBrowser();
		ReadObjectRepository object = new ReadObjectRepository();
		allObjects = object.getObject();
		operation = new SeleniumOperation(webdriver);
	}
	
	@Test
	public void testCheckDeposit() throws Exception 
	{
		ReadExcel re = new ReadExcel();
		String xllocation = System.getProperty("user.dir")+"\\TestData\\TestData.xls";
		re.setInputFile(xllocation, 0);
		String[][] data = re.readFile();
		
		try
		{	
			int CheckAmount = 10;
			Calendar cal = Calendar.getInstance();
			String Month = String.valueOf(cal.get(Calendar.DAY_OF_MONTH));
			String Hour = String.valueOf(cal.get(Calendar.HOUR));
			String Minutes = String.valueOf(cal.get(Calendar.MINUTE));
			String Seconds = String.valueOf(cal.get(Calendar.SECOND));
			String Amount = String.valueOf("10");
			//String Account_Number = String.valueOf("10768242");
			
			String CheckNumber = Month + Hour + Minutes + Seconds;
			String DepositNumber = Minutes + Seconds;
									
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			String query = "SELECT account_number FROM customer WHERE is_active = '1' AND billing_method = 'Invoice' AND email IS NOT NULL LIMIT 1";
			String Account_Number = SeleniumOperation.querydb(query, "brandywine_erp");
			
			String query1 ="SELECT running_balance FROM customer WHERE account_number = '"+Account_Number+"'";
			String Running_Balance= SeleniumOperation.querydb(query1, "brandywine_erp");
			
			//Truncating decimal values from Account_Balance
			int RunningBalanceInitial = Integer.parseInt(String.valueOf(Running_Balance).split("\\.")[0]);
			
			//Manually calculating the Final Running Balance (Running Balance is negative value of Account Balance
			int FinalRunningBalance = RunningBalanceInitial + CheckAmount;
			
			//----operation.perform(allObjects, Keyword, ObjectName, Object Type, Value)----
			operation.execute(allObjects, "ACCESSURL", "", "", data[0][3]);
			operation.execute(allObjects, "SENDKEYS", "ERP_ENTEREMAIL", "name", data[1][3]);
			operation.execute(allObjects, "SENDKEYS", "ERP_PASSWORD", "name", data[2][3]);
			operation.execute(allObjects, "CLICK", "erpLogin", "xpath", "");
			Thread.sleep(5000);
			operation.execute(allObjects, "CLICK", "Billingtab", "xpath", "");
			Thread.sleep(5000);
			operation.execute(allObjects, "CLICK", "DepostSlips", "xpath", "");
			operation.execute(allObjects, "SENDKEYS", "DepositNumber", "xpath", DepositNumber);
			operation.execute(allObjects, "SENDKEYS", "CustomerID", "xpath", Account_Number);
			operation.execute(allObjects, "SENDKEYS", "DebitAmount", "xpath", Amount);
			operation.execute(allObjects, "SENDKEYS", "CheckNo", "xpath", CheckNumber);
			operation.execute(allObjects, "CLEAR", "PayerName", "xpath", "");
			operation.execute(allObjects, "SENDKEYS", "PayerName", "xpath", "Sibin");
			Thread.sleep(3000);
			operation.execute(allObjects, "CLICK", "UploadCheck", "xpath", "");
			Thread.sleep(2000);
			webdriver.switchTo().alert().accept();
			Thread.sleep(5000);
			
			WriteTextFile objWrite = new WriteTextFile();
			String filePath = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\CheckNumber.txt";
			objWrite.Writedata(filePath, CheckNumber);
			String file_Path = System.getProperty("user.dir")+"\\TestData\\AutogeneratedTestData\\NSFAccountNumber.txt";
			objWrite.Writedata(file_Path, Account_Number);
			
			String query2 ="SELECT running_balance FROM customer WHERE account_number = '"+Account_Number+"'";
			String Balance= SeleniumOperation.querydb(query2, "brandywine_erp");
			int RunningBalanceFinal = Integer.parseInt(String.valueOf(Balance).split("\\.")[0]);
						
			Assert.assertEquals(RunningBalanceFinal,FinalRunningBalance);
			
			operation.execute(allObjects, "CLICK", "ERPLogout", "xpath", "");
			webdriver.quit();
		}
		catch (NoSuchElementException e) 
		{	
			e.printStackTrace();
			webdriver.quit();
		}
		
	}
}

